#!/usr/bin/env python3
"""Run every dashboard panel query through Grafana and report failures.

A dashboard that provisions cleanly can still be full of broken SQL -- Grafana
only finds out when a human opens the panel. Run this before demoing.
"""
import glob
import json
import os
import sys
import urllib.error
import urllib.request

# Two Grafanas: this repo's, and the SSIS engine's own on :3001. The board
# written into his provisioning folder is generated by the same script as these
# ones, so it is checked the same way -- a panel that only fails over there is
# still a panel this repo broke.
GRAFANA = os.getenv("GRAFANA_URL", "http://localhost:3000")
AUTH = "admin:admin"

HIS = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "source", "deploy", "grafana", "provisioning")) + "/"

BOARDS = [
    ("grafana/dashboards/*.json", "http://localhost:3000"),
    (HIS + "dashboards/ssis_pipeline_health.json", "http://localhost:3001"),
    (HIS + "dashboards/ssis_stream.json", "http://localhost:3001"),
]


# Read ONLY to cross-check how each Grafana's datasources are spelled.
#
# The reference for :3001 used to be his hand-written `ssis_stream.json`, on
# the grounds that it was his, it demonstrably rendered, and so whatever it
# said was what that Grafana understood. That board is now GENERATED by this
# repo too -- so using it as the reference would have compared this script's
# output against this script's output and passed no matter what. The anchor
# moved to his datasource PROVISIONING file, which is the actual ground truth
# for how his Grafana names its plugin and which nothing here ever writes.
BINDING_REFS = {
    "http://localhost:3000": sorted(glob.glob("grafana/dashboards/*.json")),
    "http://localhost:3001": [
        HIS + "datasources/datasources.yaml",
        HIS + "dashboards/ssis_pipeline_health.json",
        HIS + "dashboards/ssis_stream.json",
    ],
}

DEFAULT_DS = {"type": "grafana-postgresql-datasource", "uid": "etl-postgres"}


def query(raw_sql, fmt, ds=None, base=None):
    # Each target carries its OWN datasource: the comparison dashboard reads
    # the SSIS warehouse as well as this one, and sending its SQL to the wrong
    # datasource gets a bare "400 Bad Request" that looks like a broken query.
    body = json.dumps({
        "queries": [{
            "refId": "A",
            "datasource": ds or DEFAULT_DS,
            "format": fmt, "rawQuery": True, "rawSql": raw_sql,
            "intervalMs": 30000, "maxDataPoints": 100,
        }],
        "from": "now-30m", "to": "now",
    }).encode()
    import base64
    req = urllib.request.Request(
        f"{base or GRAFANA}/api/ds/query", data=body,
        headers={"Content-Type": "application/json",
                 "Authorization": "Basic " + base64.b64encode(
                     AUTH.encode()).decode()})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def board_datasources(path):
    """Every (uid, type) pair a board declares, panels and targets alike."""
    out = set()
    for panel in json.load(open(path))["panels"]:
        for ds in [panel.get("datasource")] + \
                  [t.get("datasource") for t in panel.get("targets", [])]:
            if ds and ds.get("uid"):
                out.add((ds["uid"], ds.get("type")))
    return out


def provisioned_datasources(path):
    """Every (uid, type) a Grafana datasource provisioning file declares.

    This is the authority, not a vote: it is what that Grafana is actually
    told its datasources are called.
    """
    import yaml
    doc = yaml.safe_load(open(path)) or {}
    return {(d["uid"], d.get("type")) for d in doc.get("datasources", [])
            if d.get("uid")}


def declared_datasources(path):
    if path.endswith((".yaml", ".yml")):
        return provisioned_datasources(path)
    return board_datasources(path)


def check_bindings():
    """One datasource uid must be spelled ONE way per Grafana.

    This exists because of a failure that produced no error anywhere. The board
    written into the SSIS repo named the Postgres plugin by the id THIS Grafana
    uses (`grafana-postgresql-datasource`, 11.3). He runs grafana-oss 11.1.7,
    where the frontend wants `postgres`. The board provisioned, the panels drew
    their titles and their frames, every query returned HTTP 200 -- and every
    panel on his screen rendered completely EMPTY, because the panel could not
    bind a datasource.

    Nothing server-side can catch that. /api/ds/query resolves a datasource by
    uid and ignores `type` completely -- it answers 200 for `postgres`, for
    `grafana-postgresql-datasource`, and for `bogus-type` alike -- so the SQL
    check below passed throughout. /api/datasources reports the type the
    BACKEND uses, which on 11.1.7 is the new id even though only the old id
    renders, so comparing against it flags the spelling that actually works.

    What is checkable is agreement: a Grafana serving two boards that spell the
    same uid differently means one of them is wrong, and the one that renders
    is the reference. So every board on a given Grafana -- including the ones
    this repo does not generate -- must agree on the spelling.
    """
    problems = []
    for base, paths in BINDING_REFS.items():
        spellings = {}
        for path in paths:
            if not os.path.exists(path):
                continue
            for uid, typ in declared_datasources(path):
                spellings.setdefault(uid, {}).setdefault(typ, []).append(
                    os.path.basename(path))
        for uid, by_type in spellings.items():
            if len(by_type) > 1:
                detail = "; ".join(
                    f"{t!r} in {', '.join(sorted(set(f)))}"
                    for t, f in sorted(by_type.items(), key=lambda kv: str(kv[0])))
                problems.append(
                    f"[{base}] datasource {uid!r} is spelled two ways -- "
                    f"{detail}. Panels whose spelling this Grafana's frontend "
                    f"does not know render EMPTY with no error anywhere.")
    return problems


def check_layout(path):
    """Every grid row must fill exactly 24 columns, with no gap and no overlap.

    Grafana silently reflows a row that does not add up -- panels slide, or one
    drops onto a line of its own -- so a width typo produces a board that looks
    subtly wrong rather than an error. Cheap to assert, and it is the thing that
    breaks when panels are added or removed.
    """
    import collections
    problems = []
    dash = json.load(open(path))
    rows = collections.defaultdict(list)
    for panel in dash["panels"]:
        rows[panel["gridPos"]["y"]].append(panel)
    for y in sorted(rows):
        ps = sorted(rows[y], key=lambda q: q["gridPos"]["x"])
        x = 0
        for panel in ps:
            if panel["gridPos"]["x"] != x:
                problems.append(
                    f"{dash['title']}: row y={y} has a gap or overlap at "
                    f"x={panel['gridPos']['x']} (expected {x}) "
                    f"-- panel {panel['title']!r}")
            x += panel["gridPos"]["w"]
        if x != 24:
            problems.append(
                f"{dash['title']}: row y={y} is {x} columns wide, not 24 "
                f"({', '.join(q['title'] for q in ps)})")
    return problems


def main() -> int:
    failures = 0
    checked = 0
    for problem in check_bindings():
        failures += 1
        print(f"FAIL  {problem}")
    for _pattern, _base in BOARDS:
        for _path in sorted(glob.glob(_pattern)):
            for problem in check_layout(_path):
                failures += 1
                print(f"FAIL  {problem}")
    paths = []
    for pattern, base in BOARDS:
        for path in sorted(glob.glob(pattern)):
            paths.append((path, base))

    for path, base in paths:
        dash = json.load(open(path))
        print(f"\n=== {dash['title']}  [{base}] ===")
        for panel in dash["panels"]:
            for tgt in panel.get("targets", []):
                checked += 1
                try:
                    result = query(tgt["rawSql"], tgt.get("format", "table"),
                                   tgt.get("datasource"), base)
                    res = result["results"]["A"]
                    if "error" in res:
                        failures += 1
                        print(f"  FAIL  {panel['title']}: {res['error'][:160]}")
                        continue
                    frames = res.get("frames", [])
                    rows = len(frames[0]["data"]["values"][0]) if frames and \
                        frames[0]["data"]["values"] else 0
                    flag = "ok  " if rows else "EMPTY"
                    uid = (tgt.get("datasource") or DEFAULT_DS)["uid"]
                    tag = "" if uid == "etl-postgres" else f"  [{uid}]"
                    print(f"  {flag}  {panel['title']}{tag} ({rows} rows)")
                except urllib.error.URLError as exc:
                    failures += 1
                    print(f"  FAIL  {panel['title']}: {exc}")
    print(f"\n{checked} queries checked, {failures} failed")
    if not failures:
        print("every panel binds a real datasource and returns rows")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
