apiVersion: 1

datasources:
  - name: ETL-Postgres
    uid: etl-postgres
    type: postgres
    access: proxy
    url: ${PG_HOST}
    database: ${PG_DB}
    user: ${PG_USER}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
