-- =====================================================================
-- GENERATED by spec/fixtures/dims.py -- do not hand-edit.
--
-- The single catalogue shared by the NiFi and SSIS engines: 18 products
-- (3.20 - 249.00) and 60 customers, taken from the SSIS side. Both
-- warehouses must hold exactly these rows or UNKNOWN_SKU and
-- UNKNOWN_CUSTOMER cannot be compared.
-- =====================================================================


-- country/segment are ADDITIVE. No SSIS rule reads them; NiFi's
-- enrich_customer stage does, and both warehouses must agree.
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS country VARCHAR(8);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS segment VARCHAR(20);


INSERT INTO public.products (sku, unit_price, category, product_name, manufacturer) VALUES
    ('SKU-0001', 12.99, 'electronics', 'USB-C Hub', 'Aurora'),
    ('SKU-0002', 89.5, 'electronics', 'Bluetooth Speaker', 'Aurora'),
    ('SKU-0003', 249.0, 'electronics', 'Noise-Cancelling Headset', 'Voltix'),
    ('SKU-0004', 32.25, 'clothing', 'Zen T-Shirt', 'Threadline'),
    ('SKU-0005', 64.0, 'clothing', 'Cloud Hoodie', 'Threadline'),
    ('SKU-0006', 18.4, 'books', 'The Data Mindset', 'Papertrail'),
    ('SKU-0007', 27.9, 'books', 'Streaming Systems 2e', 'Papertrail'),
    ('SKU-0008', 15.6, 'home', 'Ceramic Mug Set', 'Homestead'),
    ('SKU-0009', 120.0, 'home', 'Espresso Machine', 'Homestead'),
    ('SKU-0010', 22.8, 'sports', 'Trail Bottle 1L', 'Pulsegear'),
    ('SKU-0011', 95.4, 'sports', 'Resistance Band Kit', 'Pulsegear'),
    ('SKU-0012', 11.99, 'toys', 'Stacking Blocks', 'Playlab'),
    ('SKU-0013', 34.75, 'toys', 'Building Brick Set', 'Playlab'),
    ('SKU-0014', 7.95, 'beauty', 'Lip Balm Trio', 'Glowco'),
    ('SKU-0015', 49.9, 'beauty', 'Vitamin C Serum', 'Glowco'),
    ('SKU-0016', 3.2, 'grocery', 'Organic Oats 500g', 'GreenFork'),
    ('SKU-0017', 8.75, 'grocery', 'Cold Brew Can 4pk', 'GreenFork'),
    ('SKU-0018', 5.6, 'grocery', 'Almond Milk 1L', 'GreenFork')
ON CONFLICT (sku) DO NOTHING;


INSERT INTO public.customers (customer_id, customer_name, email, country, segment) VALUES
    ('CUST-00001', 'Aarav Mehta', 'user1@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00002', 'Giulia Bianchi', 'user2@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00003', 'Noah Kim', 'user3@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00004', 'Priya Nair', 'user4@streamstore.example', 'US', 'RETAIL'),
    ('CUST-00005', 'Liam O''Connor', 'user5@streamstore.example', 'GB', 'PRIME'),
    ('CUST-00006', 'Sofia Rossi', 'user6@streamstore.example', 'AE', 'RETAIL'),
    ('CUST-00007', 'Kenji Tanaka', 'user7@streamstore.example', 'SG', 'RETAIL'),
    ('CUST-00008', 'Aisha Rahman', 'user8@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00009', 'Mateo Costa', 'user9@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00010', 'Ingrid Larsen', 'user10@streamstore.example', 'IN', 'PRIME'),
    ('CUST-00011', 'Wei Zhang', 'user11@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00012', 'Fatima Haddad', 'user12@streamstore.example', 'US', 'RETAIL'),
    ('CUST-00013', 'Diego Alvarez', 'user13@streamstore.example', 'GB', 'RETAIL'),
    ('CUST-00014', 'Mia Johansson', 'user14@streamstore.example', 'AE', 'RETAIL'),
    ('CUST-00015', 'Omar Farouk', 'user15@streamstore.example', 'SG', 'PRIME'),
    ('CUST-00016', 'Hana Sato', 'user16@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00017', 'Emma Dubois', 'user17@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00018', 'Ravi Sharma', 'user18@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00019', 'Lena Novak', 'user19@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00020', 'Yusuf Demir', 'user20@streamstore.example', 'US', 'PRIME'),
    ('CUST-00021', 'Elena Petrova', 'user21@streamstore.example', 'GB', 'RETAIL'),
    ('CUST-00022', 'Arjun Chopra', 'user22@streamstore.example', 'AE', 'RETAIL'),
    ('CUST-00023', 'Camila Gomez', 'user23@streamstore.example', 'SG', 'RETAIL'),
    ('CUST-00024', 'Felix Weber', 'user24@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00025', 'Nina Kozlov', 'user25@streamstore.example', 'IN', 'WHOLESALE'),
    ('CUST-00026', 'David Chen', 'user26@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00027', 'Isabella Russo', 'user27@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00028', 'Raj Patel', 'user28@streamstore.example', 'US', 'RETAIL'),
    ('CUST-00029', 'Lea Muller', 'user29@streamstore.example', 'GB', 'RETAIL'),
    ('CUST-00030', 'Marco Silva', 'user30@streamstore.example', 'AE', 'PRIME'),
    ('CUST-00031', 'Anya Ivanova', 'user31@streamstore.example', 'SG', 'RETAIL'),
    ('CUST-00032', 'Sara Costa', 'user32@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00033', 'Tom Becker', 'user33@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00034', 'Zara Ali', 'user34@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00035', 'Lucas Meyer', 'user35@streamstore.example', 'IN', 'PRIME'),
    ('CUST-00036', 'Mei Lin', 'user36@streamstore.example', 'US', 'RETAIL'),
    ('CUST-00037', 'Olga Nowak', 'user37@streamstore.example', 'GB', 'RETAIL'),
    ('CUST-00038', 'Bruno Ferrari', 'user38@streamstore.example', 'AE', 'RETAIL'),
    ('CUST-00039', 'Eva Hansen', 'user39@streamstore.example', 'SG', 'RETAIL'),
    ('CUST-00040', 'Khalid Hassan', 'user40@streamstore.example', 'IN', 'PRIME'),
    ('CUST-00041', 'Nora Kovacs', 'user41@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00042', 'Pablo Ruiz', 'user42@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00043', 'Freya Schmidt', 'user43@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00044', 'Amir Hussain', 'user44@streamstore.example', 'US', 'RETAIL'),
    ('CUST-00045', 'Chloe Martin', 'user45@streamstore.example', 'GB', 'PRIME'),
    ('CUST-00046', 'Daniel Okafor', 'user46@streamstore.example', 'AE', 'RETAIL'),
    ('CUST-00047', 'Sigrid Berg', 'user47@streamstore.example', 'SG', 'RETAIL'),
    ('CUST-00048', 'Hugo Lindqvist', 'user48@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00049', 'Ivy Thompson', 'user49@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00050', 'Jack Wilson', 'user50@streamstore.example', 'IN', 'WHOLESALE'),
    ('CUST-00051', 'Customer 00051', 'user51@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00052', 'Customer 00052', 'user52@streamstore.example', 'US', 'RETAIL'),
    ('CUST-00053', 'Customer 00053', 'user53@streamstore.example', 'GB', 'RETAIL'),
    ('CUST-00054', 'Customer 00054', 'user54@streamstore.example', 'AE', 'RETAIL'),
    ('CUST-00055', 'Customer 00055', 'user55@streamstore.example', 'SG', 'PRIME'),
    ('CUST-00056', 'Customer 00056', 'user56@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00057', 'Customer 00057', 'user57@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00058', 'Customer 00058', 'user58@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00059', 'Customer 00059', 'user59@streamstore.example', 'IN', 'RETAIL'),
    ('CUST-00060', 'Customer 00060', 'user60@streamstore.example', 'US', 'PRIME')
ON CONFLICT (customer_id) DO UPDATE SET
    customer_name = EXCLUDED.customer_name,
    email         = EXCLUDED.email,
    country       = EXCLUDED.country,
    segment       = EXCLUDED.segment;
