"""Auto-generates a bindings.yml for a package from (a) facts already present
in the package's OWN connection managers and (b) one job's deployment target
(jobconfig.JobConfig.destination_db) -- never a hardcoded table/column name.

Adapted from the reference repo's api/app.py (_resolve_bindings /
_generate_bindings_yaml / _oledb_binding_block / _flatfile_binding_block),
generalized so the "one fixed deployment target" facts come from a job's
job.yml instead of a handful of GEN_DB_* environment constants -- the only
change needed to make the same mechanism work for any job, not just one.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

import yaml

from jobconfig import JobConfig
from ssis2nifi.dtsx.parse import NotADtsxPackage, parse_file


def _slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return s or "conn"


def _unique_key(ref_id: str, used: set[str]) -> str:
    m = re.search(r"\[([^\]]+)\]\s*$", ref_id)
    base = _slug(m.group(1) if m else ref_id)
    key, i = base, 2
    while key in used:
        key, i = f"{base}_{i}", i + 1
    used.add(key)
    return key


def _oledb_binding_block(conn, db: dict) -> dict:
    return {
        "for": conn.ref_id,
        "db_type": db.get("db_type", "PostgreSQL"),
        "identifier_case": db.get("identifier_case", "lower"),
        "url": db["url"] if "url" in db else
               f"jdbc:postgresql://{db['host']}:{db['port']}/{db['dbname']}",
        "driver_class": db.get("driver_class", "org.postgresql.Driver"),
        "driver_path": db.get("driver_path", "/opt/nifi/drivers/postgresql.jar"),
        "user": db["user"],
        "password_ref": db["password_ref"],
    }


def _flatfile_binding_block(conn, landing_dir: str) -> tuple[dict, Optional[str]]:
    """directory comes from the job's one fixed landing dir; file_filter and
    reader_kind come from the extension already present in the connection
    manager's own ConnectionString -- not invented."""
    raw = conn.properties.get("ConnectionString", "")
    ext = Path(raw.replace("\\", "/")).suffix.lstrip(".").lower()
    block = {"for": conn.ref_id, "directory": landing_dir}
    if not ext:
        block["file_filter"] = ".*"
        return block, (f"connection {conn.ref_id!r}: no file extension found in "
                        f"ConnectionString {raw!r}; file_filter defaulted to '.*' "
                        "-- please review by hand")
    if ext == "ndjson":
        block["file_filter"] = ".*\\.(json|ndjson)"
        block["reader_kind"] = "ndjson"
    else:
        block["file_filter"] = f".*\\.{ext}"
    return block, None


def generate(job: JobConfig, pkg) -> tuple[str, list[str]]:
    """Build the bindings.yml text for `pkg` under `job`'s deployment target.
    Returns (yaml_text, warnings)."""
    used: set[str] = set()
    entries: list[tuple[str, dict]] = []
    warnings: list[str] = []
    db = job.destination_db
    landing_dir = db["landing_dir"]

    for conn in pkg.connections:
        if conn.kind == "OLEDB":
            entries.append((_unique_key(conn.ref_id, used), _oledb_binding_block(conn, db)))
        elif conn.kind == "FLATFILE":
            block, warn = _flatfile_binding_block(conn, landing_dir)
            entries.append((_unique_key(conn.ref_id, used), block))
            if warn:
                warnings.append(warn)
        else:
            warnings.append(
                f"connection {conn.ref_id!r} has kind {conn.kind!r} ({conn.creation_name!r}), "
                "which this generator does not know how to bind and has left out; "
                "any component needing it will fail conversion with a clear error "
                "naming it, not a guessed binding"
            )

    doc: dict = {"bindings": dict(entries)}
    if job.ledger:
        doc["ledger"] = job.ledger

    header = (
        f"# AUTO-GENERATED by migrator/bindings.py for job {job.name!r}\n"
        f"# Source package: {pkg.name}\n"
        "#\n"
        "# Generated from (a) this job's one fixed deployment target (job.yml's\n"
        "# destination_db/nifi/ledger blocks) and (b) facts already present in the\n"
        "# package's own connection managers. Nothing here was guessed.\n"
        "#\n"
        "# Freely hand-edit or delete this file -- deleting it regenerates it the\n"
        "# same way on the next `migrator convert`/`deploy` for this job.\n"
        "#\n"
        "# NO SECRETS HERE. password_ref names an environment variable; the value\n"
        "# is never written into this file or into the generated flow.json.\n"
    )
    if warnings:
        header += "#\n# Generator warnings (review before trusting this file blindly):\n"
        header += "".join(f"#  - {w}\n" for w in warnings)

    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    return header + "\n" + body, warnings


def resolve(job: JobConfig, force_regenerate: bool = False) -> Path:
    """Return the path to this job's bindings.yml, generating it if absent
    (or if force_regenerate). Refuses loudly if the package can't be parsed --
    same as the reference repo's own default-filename-only auto-generation."""
    bindings_path = job.job_dir / "bindings.generated.yml"
    if bindings_path.is_file() and not force_regenerate:
        return bindings_path

    try:
        pkg = parse_file(str(job.package_path))
    except NotADtsxPackage as exc:
        raise SystemExit(f"refused: {exc}") from exc

    text, warnings = generate(job, pkg)
    bindings_path.write_text(text)
    if warnings:
        import sys
        print(f"[bindings] generated {bindings_path} with {len(warnings)} warning(s):",
              file=sys.stderr)
        for w in warnings:
            print(f"  - {w}", file=sys.stderr)
    return bindings_path
