-- ============================================================
-- Streaming source schema (SSIS-only swap): replaces the static
-- batch files. The orders_stream generator reads the
-- public.products / public.customers tables to build referentially
-- consistent orders; pkg_ingest_stage picks the NDJSON landing files
-- up and the simulator appends them into the existing star schema.
--
-- Also adds the per-file SSIS streaming control tables the
-- simulator / Grafana rely on.
-- ============================================================

-- ------------------------------------------------------------
-- Reference tables the generator reads (bare names -> public,
-- generator's Catalog.from_db queries products + customers).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.products (
    sku          VARCHAR(40) PRIMARY KEY,
    unit_price   NUMERIC(14,4) NOT NULL,
    category     VARCHAR(60) NOT NULL,
    product_name VARCHAR(120),
    manufacturer VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS public.customers (
    customer_id   VARCHAR(40) PRIMARY KEY,
    customer_name VARCHAR(120),
    email         VARCHAR(160)
);

-- ------------------------------------------------------------
-- Per-file SSIS streaming ledger (appears in Grafana as the
-- "batches processed / throughput" panels).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS control.stream_file (
    stream_id      BIGSERIAL PRIMARY KEY,
    source_file    VARCHAR(255) UNIQUE NOT NULL,
    etl_batch_id   BIGINT,
    lines_in       BIGINT DEFAULT 0,
    lines_clean    BIGINT DEFAULT 0,
    lines_rejected BIGINT DEFAULT 0,
    orders_loaded  BIGINT DEFAULT 0,
    revenue        NUMERIC(18,4) DEFAULT 0,
    status         VARCHAR(20) DEFAULT 'PROCESSED',
    processed_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS control.stream_alerts (
    alert_id     BIGSERIAL PRIMARY KEY,
    etl_batch_id BIGINT,
    source_file  VARCHAR(255),
    order_id     VARCHAR(30),
    customer_id  VARCHAR(40),
    alert_type   VARCHAR(40) NOT NULL,
    alert_value  NUMERIC(18,4),
    detail       JSONB,
    alert_ts     TIMESTAMPTZ DEFAULT now()
);

-- Singleton ops tile: queue depth + consumer heartbeat + latest error.
CREATE TABLE IF NOT EXISTS control.pipeline_runtime (
    singleton        SMALLINT PRIMARY KEY CHECK (singleton = 1),
    as_of            TIMESTAMPTZ NOT NULL,
    pending_files    BIGINT DEFAULT 0,
    last_batch_id    BIGINT,
    last_source_file VARCHAR(255),
    last_file_status VARCHAR(20),
    failed_jobs      BIGINT DEFAULT 0,
    last_error       TEXT
);

-- Backlog/health time series (one row per consumer poll; pruned to a few
-- hours so the queue-depth/backlog charts stay cheap).
CREATE TABLE IF NOT EXISTS control.runtime_history (
    hist_id        BIGSERIAL PRIMARY KEY,
    as_of          TIMESTAMPTZ NOT NULL,
    pending_files  BIGINT DEFAULT 0,
    failed_jobs    BIGINT DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_runtime_history_ts ON control.runtime_history(as_of);

CREATE INDEX IF NOT EXISTS ix_stream_file_batch    ON control.stream_file(etl_batch_id);
CREATE INDEX IF NOT EXISTS ix_stream_alerts_ts     ON control.stream_alerts(alert_ts);
CREATE INDEX IF NOT EXISTS ix_stream_alerts_type   ON control.stream_alerts(alert_type);
CREATE INDEX IF NOT EXISTS ix_products_sku         ON public.products(sku);
CREATE INDEX IF NOT EXISTS ix_customers_id         ON public.customers(customer_id);

-- ------------------------------------------------------------
-- Dimension seed moved to scripts/shared_dims.sql.
--
-- The products and customers seeded here are now the SHARED catalogue used
-- by both this SSIS pipeline and the NiFi pipeline it is being compared
-- against. Both warehouses must hold identical rows, or UNKNOWN_SKU and
-- UNKNOWN_CUSTOMER verdicts differ for reasons that have nothing to do with
-- the rules. The rows themselves are unchanged from this file's original
-- seed -- same 18 skus, same prices, same categories, same emails.
--
-- Generated by NIFI-FLOW/spec/fixtures/dims.py; applied by apply_sql.py.
-- ------------------------------------------------------------