#!/usr/bin/env python3
"""Generates deterministic seed SQL for the telecom reference dimensions
(dim_subscriber, dim_cell_tower, dim_plan) -- committed, not regenerated at
container start, so source and destination load byte-identical reference
data every time (a fixed seed makes this reproducible; this script is the
audit trail for where the seed file came from).

Both source/db/init/02_seed_dims.sql and destination/db/init/02_seed_dims.sql
are the SAME generated output, copied into each stack's own init directory --
source needs it to compute the "what SSIS would have loaded" ground truth,
destination needs it because the migrated NiFi flow's Lookup processors read
these tables directly (see jobs/telecom_cdr/job.yml's `Telecom Warehouse`
binding). Two independent Postgres instances, identical seed, by design --
the whole point of the two-engine comparison is that both sides start from
the same reference data and only diverge if one engine's processing logic is
wrong.
"""
from __future__ import annotations

import pathlib
import random

random.seed(20260101)  # fixed seed -> byte-identical output on every run

N_SUBSCRIBERS = 500
N_TOWERS = 30
PLANS = [
    ("PLAN_BASIC", 0.05, "USD"),
    ("PLAN_PLUS", 0.08, "USD"),
    ("PLAN_PRO", 0.12, "USD"),
    ("PLAN_UNLIMITED", 0.03, "USD"),
    ("PLAN_INTL", 0.25, "USD"),
]
CITIES = ["Austin", "Denver", "Seattle", "Miami", "Chicago", "Phoenix", "Boston", "Atlanta"]


def main() -> None:
    out = pathlib.Path(__file__).resolve().parent.parent / "_generated_seed_dims.sql"
    lines = [
        "-- GENERATED by scripts/gen_dim_seed_sql.py -- do not hand-edit, re-run the",
        "-- script instead. Copied verbatim into source/db/init/02_seed_dims.sql and",
        "-- destination/db/init/02_seed_dims.sql so both engines see identical reference",
        "-- data.",
        "",
        "INSERT INTO dim_plan (plan_code, rate_per_min, currency) VALUES",
    ]
    lines.append(",\n".join(f"  ('{code}', {rate}, '{cur}')" for code, rate, cur in PLANS) + ";")

    lines.append("\nINSERT INTO dim_cell_tower (tower_id, location) VALUES")
    towers = []
    for i in range(1, N_TOWERS + 1):
        tower_id = f"TWR{i:04d}"
        city = random.choice(CITIES)
        towers.append(f"  ('{tower_id}', '{city}')")
    lines.append(",\n".join(towers) + ";")

    lines.append("\nINSERT INTO dim_subscriber (subscriber_id, msisdn, plan_code, status) VALUES")
    subs = []
    plan_codes = [p[0] for p in PLANS]
    for i in range(1, N_SUBSCRIBERS + 1):
        sub_id = f"SUB{i:06d}"
        msisdn = f"1555{i:07d}"
        plan = random.choice(plan_codes)
        status = "active" if random.random() > 0.03 else "suspended"
        subs.append(f"  ('{sub_id}', '{msisdn}', '{plan}', '{status}')")
    lines.append(",\n".join(subs) + ";")

    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({N_SUBSCRIBERS} subscribers, {N_TOWERS} towers, {len(PLANS)} plans)")


if __name__ == "__main__":
    main()
