-- =====================================================================
-- GENERATED by spec/fixtures/dims.py -- do not hand-edit.
--
-- The single catalogue shared by the NiFi and SSIS engines: 18 products
-- (3.20 - 249.00) and 60 customers, taken from the SSIS side. Both
-- warehouses must hold exactly these rows or UNKNOWN_SKU and
-- UNKNOWN_CUSTOMER cannot be compared.
-- =====================================================================


INSERT INTO products (sku, product_name, category, unit_price, unit_cost) VALUES
    ('SKU-0001', 'USB-C Hub', 'electronics', 12.99, 8.05),
    ('SKU-0002', 'Bluetooth Speaker', 'electronics', 89.5, 55.49),
    ('SKU-0003', 'Noise-Cancelling Headset', 'electronics', 249.0, 154.38),
    ('SKU-0004', 'Zen T-Shirt', 'clothing', 32.25, 20.0),
    ('SKU-0005', 'Cloud Hoodie', 'clothing', 64.0, 39.68),
    ('SKU-0006', 'The Data Mindset', 'books', 18.4, 11.41),
    ('SKU-0007', 'Streaming Systems 2e', 'books', 27.9, 17.3),
    ('SKU-0008', 'Ceramic Mug Set', 'home', 15.6, 9.67),
    ('SKU-0009', 'Espresso Machine', 'home', 120.0, 74.4),
    ('SKU-0010', 'Trail Bottle 1L', 'sports', 22.8, 14.14),
    ('SKU-0011', 'Resistance Band Kit', 'sports', 95.4, 59.15),
    ('SKU-0012', 'Stacking Blocks', 'toys', 11.99, 7.43),
    ('SKU-0013', 'Building Brick Set', 'toys', 34.75, 21.54),
    ('SKU-0014', 'Lip Balm Trio', 'beauty', 7.95, 4.93),
    ('SKU-0015', 'Vitamin C Serum', 'beauty', 49.9, 30.94),
    ('SKU-0016', 'Organic Oats 500g', 'grocery', 3.2, 1.98),
    ('SKU-0017', 'Cold Brew Can 4pk', 'grocery', 8.75, 5.42),
    ('SKU-0018', 'Almond Milk 1L', 'grocery', 5.6, 3.47)
ON CONFLICT (sku) DO NOTHING;


INSERT INTO customers (customer_id, full_name, email, country, city, segment, signup_date) VALUES
    ('CUST-00001', 'Aarav Mehta', 'user1@streamstore.example', 'IN', 'Mumbai', 'RETAIL', DATE '2021-01-04'),
    ('CUST-00002', 'Giulia Bianchi', 'user2@streamstore.example', 'IN', 'Delhi', 'RETAIL', DATE '2021-01-07'),
    ('CUST-00003', 'Noah Kim', 'user3@streamstore.example', 'IN', 'Hyderabad', 'RETAIL', DATE '2021-01-10'),
    ('CUST-00004', 'Priya Nair', 'user4@streamstore.example', 'US', 'Pune', 'RETAIL', DATE '2021-01-13'),
    ('CUST-00005', 'Liam O''Connor', 'user5@streamstore.example', 'GB', 'Chennai', 'PRIME', DATE '2021-01-16'),
    ('CUST-00006', 'Sofia Rossi', 'user6@streamstore.example', 'AE', 'Kolkata', 'RETAIL', DATE '2021-01-19'),
    ('CUST-00007', 'Kenji Tanaka', 'user7@streamstore.example', 'SG', 'Ahmedabad', 'RETAIL', DATE '2021-01-22'),
    ('CUST-00008', 'Aisha Rahman', 'user8@streamstore.example', 'IN', 'Bengaluru', 'RETAIL', DATE '2021-01-25'),
    ('CUST-00009', 'Mateo Costa', 'user9@streamstore.example', 'IN', 'Mumbai', 'RETAIL', DATE '2021-01-28'),
    ('CUST-00010', 'Ingrid Larsen', 'user10@streamstore.example', 'IN', 'Delhi', 'PRIME', DATE '2021-01-31'),
    ('CUST-00011', 'Wei Zhang', 'user11@streamstore.example', 'IN', 'Hyderabad', 'RETAIL', DATE '2021-02-03'),
    ('CUST-00012', 'Fatima Haddad', 'user12@streamstore.example', 'US', 'Pune', 'RETAIL', DATE '2021-02-06'),
    ('CUST-00013', 'Diego Alvarez', 'user13@streamstore.example', 'GB', 'Chennai', 'RETAIL', DATE '2021-02-09'),
    ('CUST-00014', 'Mia Johansson', 'user14@streamstore.example', 'AE', 'Kolkata', 'RETAIL', DATE '2021-02-12'),
    ('CUST-00015', 'Omar Farouk', 'user15@streamstore.example', 'SG', 'Ahmedabad', 'PRIME', DATE '2021-02-15'),
    ('CUST-00016', 'Hana Sato', 'user16@streamstore.example', 'IN', 'Bengaluru', 'RETAIL', DATE '2021-02-18'),
    ('CUST-00017', 'Emma Dubois', 'user17@streamstore.example', 'IN', 'Mumbai', 'RETAIL', DATE '2021-02-21'),
    ('CUST-00018', 'Ravi Sharma', 'user18@streamstore.example', 'IN', 'Delhi', 'RETAIL', DATE '2021-02-24'),
    ('CUST-00019', 'Lena Novak', 'user19@streamstore.example', 'IN', 'Hyderabad', 'RETAIL', DATE '2021-02-27'),
    ('CUST-00020', 'Yusuf Demir', 'user20@streamstore.example', 'US', 'Pune', 'PRIME', DATE '2021-03-02'),
    ('CUST-00021', 'Elena Petrova', 'user21@streamstore.example', 'GB', 'Chennai', 'RETAIL', DATE '2021-03-05'),
    ('CUST-00022', 'Arjun Chopra', 'user22@streamstore.example', 'AE', 'Kolkata', 'RETAIL', DATE '2021-03-08'),
    ('CUST-00023', 'Camila Gomez', 'user23@streamstore.example', 'SG', 'Ahmedabad', 'RETAIL', DATE '2021-03-11'),
    ('CUST-00024', 'Felix Weber', 'user24@streamstore.example', 'IN', 'Bengaluru', 'RETAIL', DATE '2021-03-14'),
    ('CUST-00025', 'Nina Kozlov', 'user25@streamstore.example', 'IN', 'Mumbai', 'WHOLESALE', DATE '2021-03-17'),
    ('CUST-00026', 'David Chen', 'user26@streamstore.example', 'IN', 'Delhi', 'RETAIL', DATE '2021-03-20'),
    ('CUST-00027', 'Isabella Russo', 'user27@streamstore.example', 'IN', 'Hyderabad', 'RETAIL', DATE '2021-03-23'),
    ('CUST-00028', 'Raj Patel', 'user28@streamstore.example', 'US', 'Pune', 'RETAIL', DATE '2021-03-26'),
    ('CUST-00029', 'Lea Muller', 'user29@streamstore.example', 'GB', 'Chennai', 'RETAIL', DATE '2021-03-29'),
    ('CUST-00030', 'Marco Silva', 'user30@streamstore.example', 'AE', 'Kolkata', 'PRIME', DATE '2021-04-01'),
    ('CUST-00031', 'Anya Ivanova', 'user31@streamstore.example', 'SG', 'Ahmedabad', 'RETAIL', DATE '2021-04-04'),
    ('CUST-00032', 'Sara Costa', 'user32@streamstore.example', 'IN', 'Bengaluru', 'RETAIL', DATE '2021-04-07'),
    ('CUST-00033', 'Tom Becker', 'user33@streamstore.example', 'IN', 'Mumbai', 'RETAIL', DATE '2021-04-10'),
    ('CUST-00034', 'Zara Ali', 'user34@streamstore.example', 'IN', 'Delhi', 'RETAIL', DATE '2021-04-13'),
    ('CUST-00035', 'Lucas Meyer', 'user35@streamstore.example', 'IN', 'Hyderabad', 'PRIME', DATE '2021-04-16'),
    ('CUST-00036', 'Mei Lin', 'user36@streamstore.example', 'US', 'Pune', 'RETAIL', DATE '2021-04-19'),
    ('CUST-00037', 'Olga Nowak', 'user37@streamstore.example', 'GB', 'Chennai', 'RETAIL', DATE '2021-04-22'),
    ('CUST-00038', 'Bruno Ferrari', 'user38@streamstore.example', 'AE', 'Kolkata', 'RETAIL', DATE '2021-04-25'),
    ('CUST-00039', 'Eva Hansen', 'user39@streamstore.example', 'SG', 'Ahmedabad', 'RETAIL', DATE '2021-04-28'),
    ('CUST-00040', 'Khalid Hassan', 'user40@streamstore.example', 'IN', 'Bengaluru', 'PRIME', DATE '2021-05-01'),
    ('CUST-00041', 'Nora Kovacs', 'user41@streamstore.example', 'IN', 'Mumbai', 'RETAIL', DATE '2021-05-04'),
    ('CUST-00042', 'Pablo Ruiz', 'user42@streamstore.example', 'IN', 'Delhi', 'RETAIL', DATE '2021-05-07'),
    ('CUST-00043', 'Freya Schmidt', 'user43@streamstore.example', 'IN', 'Hyderabad', 'RETAIL', DATE '2021-05-10'),
    ('CUST-00044', 'Amir Hussain', 'user44@streamstore.example', 'US', 'Pune', 'RETAIL', DATE '2021-05-13'),
    ('CUST-00045', 'Chloe Martin', 'user45@streamstore.example', 'GB', 'Chennai', 'PRIME', DATE '2021-05-16'),
    ('CUST-00046', 'Daniel Okafor', 'user46@streamstore.example', 'AE', 'Kolkata', 'RETAIL', DATE '2021-05-19'),
    ('CUST-00047', 'Sigrid Berg', 'user47@streamstore.example', 'SG', 'Ahmedabad', 'RETAIL', DATE '2021-05-22'),
    ('CUST-00048', 'Hugo Lindqvist', 'user48@streamstore.example', 'IN', 'Bengaluru', 'RETAIL', DATE '2021-05-25'),
    ('CUST-00049', 'Ivy Thompson', 'user49@streamstore.example', 'IN', 'Mumbai', 'RETAIL', DATE '2021-05-28'),
    ('CUST-00050', 'Jack Wilson', 'user50@streamstore.example', 'IN', 'Delhi', 'WHOLESALE', DATE '2021-05-31'),
    ('CUST-00051', 'Customer 00051', 'user51@streamstore.example', 'IN', 'Hyderabad', 'RETAIL', DATE '2021-06-03'),
    ('CUST-00052', 'Customer 00052', 'user52@streamstore.example', 'US', 'Pune', 'RETAIL', DATE '2021-06-06'),
    ('CUST-00053', 'Customer 00053', 'user53@streamstore.example', 'GB', 'Chennai', 'RETAIL', DATE '2021-06-09'),
    ('CUST-00054', 'Customer 00054', 'user54@streamstore.example', 'AE', 'Kolkata', 'RETAIL', DATE '2021-06-12'),
    ('CUST-00055', 'Customer 00055', 'user55@streamstore.example', 'SG', 'Ahmedabad', 'PRIME', DATE '2021-06-15'),
    ('CUST-00056', 'Customer 00056', 'user56@streamstore.example', 'IN', 'Bengaluru', 'RETAIL', DATE '2021-06-18'),
    ('CUST-00057', 'Customer 00057', 'user57@streamstore.example', 'IN', 'Mumbai', 'RETAIL', DATE '2021-06-21'),
    ('CUST-00058', 'Customer 00058', 'user58@streamstore.example', 'IN', 'Delhi', 'RETAIL', DATE '2021-06-24'),
    ('CUST-00059', 'Customer 00059', 'user59@streamstore.example', 'IN', 'Hyderabad', 'RETAIL', DATE '2021-06-27'),
    ('CUST-00060', 'Customer 00060', 'user60@streamstore.example', 'US', 'Pune', 'PRIME', DATE '2021-06-30')
ON CONFLICT (customer_id) DO NOTHING;
